type Query {
  post(id: ID!): Post!
  posts(newest: Boolean): [Post]!
}

type Mutation {
  createPost(title: String!, content: String, tags: [String]!): String!
}

type Post {
  id: ID!
  title: String!
  content: String!
  tags: [String]!
  upvotes: Int!
  downvotes: Int!
  supervotes: Int!
  createdAt: String!
}
