type Query {
  post(id: ID!): Post!
  posts(newest: Boolean): [Post]!
  user(id: ID!): User!
}

type Mutation {
  createPost(authorId: ID!, title: String!, content: String, tags: [String]!): String!
  registerUser(alias: String!, email: String!, password: String!): String!
}

type Post {
  id: ID!
  author: User!
  title: String!
  content: String!
  tags: [String]!
  upvotes: Int!
  downvotes: Int!
  supervotes: Int!
  createdAt: String!
}

type User {
  id: ID!
  tag: String!
  tagNumber: String!
  alias: String!
  bio: String
  posts: [Post]!
  createdAt: String
}
